# Ensemble methods
## Marcin Biela 302959

In [36]:
import numpy as np
import pandas as pd 
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.model_selection import cross_val_score

In [37]:
# Load dataset
data = load_wine()

In [38]:
X = data['data']
y = data['target']

In [39]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [40]:
decissionTreeClf = DecisionTreeClassifier(random_state=1, min_samples_leaf=3)
decissionTreeCv = cross_val_score(decissionTreeClf, X, y)
decissionTreeCv

array([0.94444444, 0.80555556, 0.80555556, 0.91428571, 0.97142857])

In [41]:
baggingClf = BaggingClassifier(base_estimator=decissionTreeClf, n_estimators=50, random_state=1)
baggingClf.fit(X, y)
baggingClassifierCv = cross_val_score(baggingClf, X, y)
baggingClassifierCv

array([0.91666667, 0.91666667, 0.94444444, 0.97142857, 1.        ])

In [42]:
adaBoostClf = AdaBoostClassifier(algorithm='SAMME', n_estimators=50, random_state=1)
adaBoostClf.fit(X, y)
adaBoostClassifierCV = cross_val_score(adaBoostClf, X, y)
adaBoostClassifierCV

array([0.83333333, 0.91666667, 0.91666667, 1.        , 1.        ])

In [43]:
gradientBoostingClf =  GradientBoostingClassifier(learning_rate=1.0, subsample=0.5, n_estimators=50, min_samples_leaf=3, max_depth=1)
gradientBoostingClf.fit(X, y)
gradientBoostingCv = cross_val_score(gradientBoostingClf, X, y)
gradientBoostingCv

array([0.47222222, 0.69444444, 1.        , 0.85714286, 0.97142857])

In [ ]:
result = f"Decission Tree scores: {c}"